default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('POSTGRESQL_HOST', '') %>
  password: <%= ENV.fetch('POSTGRESQL_PASSWORD', '') %>
  username: <%= ENV.fetch('POSTGRESQL_USERNAME', '') %>
development:
  <<: *default
  database: smart_url_development
test:
  <<: *default
  database: smart_url_test

production:
  url: <%= ENV['DATABASE_URL'] %>
